version: '3.8'
services:
  mysql-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
